version: "3.3"

services:
  model_tensorboard:
    container_name: model_tensorboard
    #command: tensorboard --logdir /runs --bind_all
    command: tensorboard --logdir /runs --host 0.0.0.0
    build:
      context: .
      dockerfile: ./Tensorboard.Dockerfile
    #network_mode: host
    ipc: host
    ports:
      - "6006:6006"
    environment:
      CONTAINER: tensorboard
    volumes:
      - training_runs:/runs
  model_training:
    container_name: model_training
    command: python -m modeling.train_model
    build:
      context: .
      dockerfile: ./Training.Dockerfile
    #network_mode: host
    ipc: host
    environment:
      CONTAINER: training
    volumes:
      - training_runs:/runs
#    deploy:
#      resources:
#        reservations:
#          devices:
#            -   driver: nvidia
#                count: 1
#                capabilities: [ gpu ]

volumes:
  training_runs: